name: Build Reservationform on S3

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

  push:
    branches:
      - main

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up build directory
        run: rm -rf build

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16  # Node.jsのバージョンを16に維持

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci
          npm install react@18 react-dom@18 --legacy-peer-deps
          npm install -D tailwindcss@latest postcss@latest autoprefixer@latest --legacy-peer-deps
          npm install framer-motion lucide-react react-datepicker --legacy-peer-deps

      - name: Setup Tailwind CSS
        run: |
          npx tailwindcss init -p
          echo "module.exports = {content: ['./src/**/*.{js,jsx,ts,tsx}'],theme: {extend: {},},plugins: [],}" > tailwind.config.js
          echo "@tailwind base;@tailwind components;@tailwind utilities;" > src/index.css

      - name: Build
        run: npm run build

      - name: Configure AWS CLI
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ap-northeast-1
      
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          aws s3 sync --delete --region ap-northeast-1 --exclude "README.md" ./build s3://studiozebra-1st-reservation-form/reservation-form

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E36NOONM5TQTGN --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}