name: Deploy to AWS Lambda

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ap-northeast-1

    - name: Build Docker image
      run: docker build --platform linux/arm64 -t docker-image:test .

    - name: Tag Docker image
      run: docker tag docker-image:test 807357942906.dkr.ecr.ap-northeast-1.amazonaws.com/zebra-reservation-form:latest

    - name: Push Docker image to ECR
      run: docker push 807357942906.dkr.ecr.ap-northeast-1.amazonaws.com/zebra-reservation-form:latest

    - name: Update Lambda function
      run: |
        aws lambda update-function-code \
          --function-name reservationform-send-mail \
          --image-uri 807357942906.dkr.ecr.ap-northeast-1.amazonaws.com/zebra-reservation-form:latest \
          --architectures arm64
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
