name: Build Reservationform on S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_S3 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # パーソナルアクセストークンの使用
        run: |
          aws s3 cp --recursive --region ap-northeast-1 build s3://studiozebra-1st-reservation-form