name: Build Reservationform on S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to S3
      run: aws s3 sync build/ s3://studiozebra-1st-reservation-form

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Invalidate CloudFront cache
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_S3 }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
        aws configure set region ap-northeast-1
        aws cloudfront create-invalidation --distribution-id E36NOONM5TQTGN --paths '/*'
